version: '3.8'

services:
  app:
    build: .
    environment:
      - RUNNING_IN_DOCKER=true        
    networks:
      - app-network

  postgres_db:
    image: postgres
    environment:
      POSTGRES_PASSWORD: "test_p@ssword_f0r_CI!"
    ports:
      - "5432:5432"
    networks:
      - app-network
      
  mssql_db:
    image: mcr.microsoft.com/mssql/server:2019-latest
    environment:
      SA_PASSWORD: "test_p@ssword_f0r_CI!"
      ACCEPT_EULA: "Y"
    ports:
      - "1433:1433"
    networks:
      - app-network
  
  oracle_db:
    image: container-registry.oracle.com/database/express:latest
    environment:
      ORACLE_PWD: "test_p@ssword_f0r_CI!"
    ports:
      - "1521:1521"
    networks:
      - app-network
  
  mysql_db:
    image: mysql
    environment:
      MYSQL_ROOT_PASSWORD: "test_p@ssword_f0r_CI!"
    ports:
      - "3306:3306"
    networks:
      - app-network

networks:
  app-network:
