version: '3.8'

services:
  app:
    build: .
    depends_on:
      postgres_db:
        condition: service_started
    networks:
      - app-network
    command: ["/app/tests/integration/setup/docker-entrypoint.sh"]

  postgres_db:
    image: postgres
    environment:
      POSTGRES_PASSWORD: mysecretpassword
    ports:
      - "5432:5432"
    networks:
      - app-network

networks:
  app-network:
