version: '3.8'

services:
  app:
    build: .
    depends_on:
      postgres_db:
        condition: service_started
    environment:
      - RUNNING_IN_DOCKER=true        
    networks:
      - app-network
    command: ["./tests/integration/setup/docker-entrypoint.sh"]

  postgres_db:
    image: postgres
    environment:
      POSTGRES_PASSWORD: "mysecretpassword"
    ports:
      - "5432:5432"
    networks:
      - app-network
      
  mssql_db:
    image: mcr.microsoft.com/mssql/server:2019-latest
    environment:
      SA_PASSWORD: "MySecretPassw0rd!"
      ACCEPT_EULA: "Y"
    ports:
      - "1433:1433"
    networks:
      - app-network

networks:
  app-network:
