on:
  push:
    branches:
      - integration-tests
  pull_request:
    branches:
      - integration-tests
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Build the Docker image
      run: docker-compose build

    - name: Check code formatting with Black
      run: docker-compose run app black --check .

    - name: Checkout code
      uses: actions/checkout@v2

    - name: Start Docker Compose Services
      run: docker-compose up -d

    - name: Run Pytest
      run: docker-compose run --rm app python -m pytest

    - name: Stop and Remove Containers
      run: docker-compose down