on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Build the Docker image
      run: docker-compose build

    - name: Check code formatting with Black
      run: docker-compose run app black --check .

    - name: Run PyTest
      run: docker-compose run app pytest